[package]
name = "sbbw-widget-conf"
version = "0.1.2"
authors = ["Sergio Ribera"]
edition = "2021"

[dependencies]
toml = "0.5"
colored = "2.0.0"
dirs = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
